# Generated by Django 4.2.10 on 2024-02-21 12:24

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('emp_remark', models.CharField(max_length=250)),
                ('called_datetime', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('called_meadium', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_no', models.IntegerField()),
                ('date_time_added', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('lead_given_date', models.DateField()),
                ('lead_no', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('place', models.CharField(max_length=50)),
                ('remark', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Folloup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_no', models.IntegerField()),
                ('remark', models.CharField(max_length=250)),
                ('call_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeFAapp.calldetails')),
            ],
        ),
        migrations.AddField(
            model_name='calldetails',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeFAapp.lead'),
        ),
    ]
