# Generated by Django 4.2.10 on 2024-02-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeFAapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldetails',
            name='updated_by',
            field=models.CharField(default='', max_length=50),
        ),
    ]
