# Generated by Django 4.2.10 on 2024-02-22 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeFAapp', '0003_consts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consts',
        ),
    ]
