# Generated by Django 4.2.10 on 2024-02-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeFAapp', '0004_delete_consts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calldetails',
            name='status',
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
