# Generated by Django 4.2.10 on 2024-02-23 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeFAapp', '0005_remove_calldetails_status_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_no',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\-]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
