# Generated by Django 4.2.10 on 2024-02-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeFAapp', '0007_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('emp_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
