# Generated by Django 4.2.10 on 2024-02-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeFAapp', '0008_employee_details_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='emp_id',
            field=models.CharField(max_length=10),
        ),
    ]
