# Generated by Django 4.2.10 on 2024-02-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeFAapp', '0011_rename_employee_name_calldetails_calls_made_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folloup',
            name='control_no',
        ),
        migrations.AddField(
            model_name='calldetails',
            name='followups',
            field=models.IntegerField(default=0),
        ),
    ]
