# Generated by Django 4.2.10 on 2024-02-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeFAapp', '0012_remove_folloup_control_no_calldetails_followups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calldetails',
            name='followups',
        ),
        migrations.AddField(
            model_name='folloup',
            name='followups',
            field=models.IntegerField(default=0),
        ),
    ]
