# Generated by Django 4.2.10 on 2024-02-27 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeFAapp', '0013_remove_calldetails_followups_folloup_followups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folloup',
            name='call_detail',
        ),
    ]
