# Generated by Django 4.2.10 on 2024-02-27 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeFAapp', '0014_remove_folloup_call_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldetails',
            name='folloup',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TeFAapp.folloup'),
        ),
    ]
