# Generated by Django 4.2.10 on 2024-02-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeFAapp', '0015_calldetails_folloup'),
    ]

    operations = [
        migrations.AddField(
            model_name='folloup',
            name='control_no',
            field=models.IntegerField(default=0),
        ),
    ]
