# Generated by Django 4.2.10 on 2024-02-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeFAapp', '0016_folloup_control_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calldetails',
            name='folloup',
        ),
        migrations.AddField(
            model_name='calldetails',
            name='no_of_followups',
            field=models.IntegerField(default=0),
        ),
    ]
