# Generated by Django 4.2.10 on 2024-02-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeFAapp', '0017_remove_calldetails_folloup_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Folloup',
        ),
    ]
