# Generated by Django 4.2.10 on 2024-02-27 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeFAapp', '0018_delete_folloup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folloup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=250)),
                ('followups', models.IntegerField(default=0)),
                ('calldetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeFAapp.calldetails')),
            ],
        ),
    ]
