# Generated by Django 4.2.10 on 2024-02-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeFAapp', '0019_folloup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldetails',
            name='no_of_followups',
            field=models.IntegerField(default=1),
        ),
    ]
