# Generated by Django 4.2.10 on 2024-02-27 09:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeFAapp', '0020_alter_calldetails_no_of_followups'),
    ]

    operations = [
        migrations.AddField(
            model_name='folloup',
            name='called_datetime',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='folloup',
            name='called_meadium',
            field=models.CharField(default='phone', max_length=10),
        ),
        migrations.AddField(
            model_name='folloup',
            name='calls_made',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='follo_calls_made', to='TeFAapp.employee_details'),
        ),
        migrations.AddField(
            model_name='folloup',
            name='calls_updated',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='follo_calls_updated', to='TeFAapp.employee_details'),
        ),
        migrations.AddField(
            model_name='folloup',
            name='lead',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TeFAapp.lead'),
        ),
    ]
