# Generated by Django 4.2.10 on 2024-03-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeFAapp', '0025_lead_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='course_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
