# Generated by Django 4.2.2 on 2024-03-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeFAapp', '0027_alter_lead_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
