# Generated by Django 4.2.2 on 2024-03-24 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeFAapp', '0030_alter_lead_lead_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='course',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='course_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='degree',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_no',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z\\-]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='place',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='remark',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(default='', max_length=100),
        ),
    ]
